/*
 * Copyright (c) 2025 ZED Interactive. All Rights Reserved.
 */

#ifndef MOUSE_BUTTON_CODES_H
#define MOUSE_BUTTON_CODES_H

#pragma once

// From glfw3.h
#define SANDBOX_MOUSE_BUTTON_1     0
#define SANDBOX_MOUSE_BUTTON_2     1
#define SANDBOX_MOUSE_BUTTON_3     2
#define SANDBOX_MOUSE_BUTTON_4     3
#define SANDBOX_MOUSE_BUTTON_5     4
#define SANDBOX_MOUSE_BUTTON_6     5
#define SANDBOX_MOUSE_BUTTON_7     6
#define SANDBOX_MOUSE_BUTTON_8     7
#define SANDBOX_MOUSE_BUTTON_LAST  SANDBOX_MOUSE_BUTTON_8
#define SANDBOX_MOUSE_BUTTON_LEFT  SANDBOX_MOUSE_BUTTON_1
#define SANDBOX_MOUSE_BUTTON_RIGHT SANDBOX_MOUSE_BUTTON_2
#define SANDBOX_MOUSE_BUTTON_MIDDLE SANDBOX_MOUSE_BUTTON_3

#endif